server:
  port: 8097

  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: BOOKMS

  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bookdb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

#spring:
  devtools:
    add-properties: false

  security:
    enabled: true
    user:
      name: Edureka
      password: password
      roles: USER, ADMIN

    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json
#  security:
#    enabled: true
#    user:
#      name: Edureka
#      password: password
#      roles: USER, ADMIN
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: "https://api.asgardeo.io/t/imeshaorg/oauth2/token"


#    enabled: false
##spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
#spring.
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

app:
  security:
    cors:
      origin: http://localhost:3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    #preferIpAddress: true
    hostname: localhost

management:
#  security:
#    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

# Actuator endpoints for Circuit Breaker
  #management:    health:      circuitbreakers:        enabled: true
  #management.endpoints.web.exposure.include=health
  #management.endpoint.health.show-details=always

# Security enable/disable
#security:
#  ignored: /**
#  basic:
#    enabled: false

  ####
logging:
  file:
    #name: '/var/log/app.log'
    path: tmp/log