# main project docker-compose.yml
version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    image: kwabena81/eureka-image:0.1
    build: 
      context: ./eureka-server   
      dockerfile: Dockerfile 
    ports:
      - '8761:8761'
    expose:
      - '8761'
    networks:
      - ms_networks
    volumes: 
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro' 

  api-gateway:
    container_name: api-gateway
    image: kwabena81/api-gateway-image:0.1
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile 
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - '9797:9797'
    expose:
      - '9797'
    networks:
      - ms_networks
    volumes: 
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro' 

networks:
  ms_networks:
    name: ms_networks
    driver: bridge


  # oauth2:
  #   container_name: issueoauth2rms
  #   build: 
  #     context: ./oauth2   
  #     dockerfile: Dockerfile 
  #   environment:
  #     - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
  #   depends_on:
  #     - eureka-server
  #   ports:
  #     - '9195:9195'
  #   networks:
  #         - ms_networks
  #   volumes:
  #     - '/etc/timezone:/etc/timezone:ro'
  #     - '/etc/localtime:/etc/localtime:ro'

  # issuerms:
  #   container_name: issuerms
  #   build: 
  #     context: ./issuerms   
  #     dockerfile: Dockerfile 
  #   environment:
  #     - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
  #   depends_on:
  #     - eureka-server
  #   ports:
  #     - '8099:8099'
  #   networks:
  #         - ms_networks
  #   volumes:
  #     - '/etc/timezone:/etc/timezone:ro'
  #     - '/etc/localtime:/etc/localtime:ro'

  # bookms:
  #   container_name: bookms
  #   build: 
  #     context: ./bookms   
  #     dockerfile: Dockerfile 
  #   environment:
  #     - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
  #   depends_on:
  #     - eureka-server
  #   ports:
  #     - '8097:8097'
  #   networks:
  #         - ms_networks
  #   volumes:
  #     - '/etc/timezone:/etc/timezone:ro'
  #     - '/etc/localtime:/etc/localtime:ro'

