server:
  port: 8093

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      # http://localhost:8080/dummy-bookms/books -> http://localhost:8081/books
      routes:
        - id: BOOKMS
          uri: lb://BOOKMS
          predicates:
            - Path=/book/**       # /dummy-bookms/**
          filters:
            - RewritePath= /dummy-bookms/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: book-microservice
                fallbackuri: forward:/bookFallBack
#

        - id: issuerms
          uri: lb://ISSUERMS
          predicates:
            - Path=/issuer/**     # /dummy-issuerms/**
          filters:
            - RewritePath= /dummy-issuerms/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: issuer-microservice
                fallbackuri: forward:/issuerFallBack


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


hystrix:
  command:
    fallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


