global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.files"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9095']

  - job_name: 'bookms'     #  'spring-actuator'
    metrics_path: '/actuator/bookms'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8090']

  - job_name: 'issuerms'   #  'spring-actuator'
    metrics_path: '/actuator/issuerms'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:8090' ]

  - job_name: 'api-gateway'   #  'spring-actuator'
    metrics_path: '/actuator/api-gateway'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:8090' ]