server:
  port: 8099

spring:
  application:
    name: ISSUERMS

  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:issuerdb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      password: asksef@
#  security:
#    enabled: false
#  #spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    #preferIpAddress: true
    hostname: localhost


logging:
  file: #issuer.log
    #name: '/var/log/app.log'
    path: tmp/log


management:
  endpoints:
    web:
      exposure:
        include: "*"