global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.files"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9095']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:10088']