
server:
  port: 9898

spring:
  application:
    name: HYSTRIX-DASHBOARD

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#
management:
  endpoint:
    service-registry:
      cache:
        time-to-live: 5000

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
    #proxyStreamAllowList: hystrix.stream

#    hystrix:
#      stream:
#        enabled: true

#    management:
#      endpoints:
#        web:
#          exposure:
#            include: hystrix.stream



#hystrix:
#    stream:
#        enabled: true

