
server:
  port: 9898

spring:
  application:
    name: hystrix

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

#
management:
  endpoint:
    service-registry:
      cache:
        time-to-live: 5000
  metrics:
    export:
      prometheus:
        enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

    #proxyStreamAllowList: hystrix.stream
#    hystrix:
#      stream:
#        enabled: true
#
#  management:
#    enable-ignore-connection-close-header:
#      endpoints:
#        web:
#          exposure:
#            include: hystrix.stream



#hystrix:
#    stream:
#        enabled: true

