
server:
  port: 9195
#  servlet:
#    context-path:

spring:
#  h2:
#    console:
#      enabled: true
#
  application:
    name: OAUTH2
    servlet:
      context-path: /oauth2
    use-forward-headers: false

  security:
    enabled: true
    user:
      name: Edureka
      password: password
      roles: USER, ADMIN

    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

#  main:
#    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


logging:
  level:
    org.springframework.security: DEBUG




#    oauth2:
#      client:
#        registration:
#          github.client-id:
#          github.client-secret: