
server:
  port: 9195
#  servlet:
#    context-path:

spring:
#  h2:
#    console:
#      enabled: true
#
  application:
    name: OAUTH2-SERVER
    servlet:
      context-path: /oauth2
    use-forward-headers: false

  security:
    enabled: true
    user:
      name: Edureka
      password: $2b$12$tcoaaq3PeqkerTb8OS2t5eTBKZFzrnFPJy.s1Fk8OcIZg0aQvUyeq
      roles: USER, ADMIN

    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

#  main:
#    allow-bean-definition-overriding: true

#eureka:
#  instance:
#    hostname: localhost
#    port: 8761
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    hostname: localhost

logging:
  level:
    org.springframework.security: DEBUG




#    oauth2:
#      client:
#        registration:
#          github.client-id:
#          github.client-secret: